package ee.schimke.composeai.cli

import ee.schimke.composeai.cli.serve.PreviewHistory
import ee.schimke.composeai.cli.serve.PreviewHistoryManifest
import java.io.File
import kotlin.system.exitProcess

/**
 * Writes `history.json` for a published delivery branch: the precomputed per-preview render
 * timeline the hosted viewer reads. Driven by the publish pipeline (defaults match it), but a
 * normal command so it is testable and can be regenerated by hand.
 *
 * Unlike [HistoryCommand] (the daemon's reporting branch, per-preview sidecars, interactive), this
 * reads a CI delivery branch and emits one static file; see [PreviewHistoryManifest].
 *
 * `--layout renders` (default) is a baseline branch joined via `baselines.json`; `--layout images`
 * is a design catalog branch (`images/<slug>/<variant>.png`) whose paths are the ids
 * ([PreviewHistoryManifest.Layout]).
 *
 * ```
 * compose-preview inspect history-manifest [--branch REF] [--repo DIR] [--output FILE]
 *                                          [--layout renders|images] [--baselines FILE] [--quiet]
 * ```
 *
 * `--branch` is any resolvable ref. `--baselines` overrides where `baselines.json` comes from (by
 * default the same ref, so both are one snapshot); ignored for `--layout images`.
 */
class HistoryManifestCommand(
  private val args: List<String>,
  private val workingDir: File = File("."),
  private val stdout: (String) -> Unit = ::println,
  private val stderr: (String) -> Unit = System.err::println,
  private val readBaselines: (File, String, String) -> String? = ::gitShow,
  /** Injectable so the refuse-to-publish paths below are testable without killing the JVM. */
  private val exit: (Int) -> Nothing = { exitProcess(it) },
) {

  fun run() {
    if ("--help" in args || "-h" in args) {
      stdout(USAGE)
      return
    }

    val branch = args.valueOf("--branch") ?: DEFAULT_BRANCH
    val repoDir = args.valueOf("--repo")?.let { File(it) } ?: workingDir
    val output = File(args.valueOf("--output") ?: PreviewHistoryManifest.FILE_NAME)
    val quiet = "--quiet" in args

    // Defaults to the baseline layout, preserving existing invocations.
    val layoutArg = args.valueOf("--layout")
    val layout = PreviewHistoryManifest.Layout.of(layoutArg ?: DEFAULT_LAYOUT.name)
    if (layout == null) {
      stderr(
        "compose-preview history-manifest: unknown --layout '$layoutArg'; expected one of " +
          PreviewHistoryManifest.Layout.entries.joinToString(", ") { it.name.lowercase() } +
          "."
      )
      exit(1)
    }

    // A design-catalog branch needs no `baselines.json`: its ids are the flattened paths.
    val baselinesJson =
      if (layout != PreviewHistoryManifest.Layout.RENDERS) null
      else
        args.valueOf("--baselines")?.let { path ->
          val file = File(path)
          if (!file.isFile) {
            stderr("compose-preview history-manifest: no baselines file at ${file.path}.")
            exit(1)
          }
          file.readText()
        } ?: readBaselines(repoDir, branch, "baselines.json")

    if (layout == PreviewHistoryManifest.Layout.RENDERS && baselinesJson == null) {
      // Without baselines.json every timeline would be dropped, publishing a falsely empty
      // manifest; fail.
      stderr(
        "compose-preview history-manifest: could not read baselines.json from '$branch'. " +
          "Pass --baselines to point at it explicitly."
      )
      exit(1)
    }

    val pathToPreviewId = baselinesJson?.let { PreviewHistoryManifest.renderPathsToPreviewIds(it) }
    if (baselinesJson != null && pathToPreviewId.isNullOrEmpty()) {
      stderr(
        "compose-preview history-manifest: baselines.json from '$branch' yielded no usable " +
          "entries; refusing to write an empty manifest."
      )
      exit(1)
    }

    // Resolve the ref first: a bad ref otherwise reads as "no history" and the publish step would
    // overwrite a good manifest with an empty one.
    if (resolveSha(repoDir, branch) == null) {
      stderr(
        "compose-preview history-manifest: '$branch' is not a ref this repository can resolve."
      )
      exit(1)
    }

    // Anchor to the newest commit touching this layout's directory, not the branch tip (which the
    // manifest commit itself moves), so a no-op run regenerates a byte-identical file instead of
    // appending a history commit every time.
    val generatedFrom =
      renderTip(repoDir, branch, layout.dir) ?: resolveSha(repoDir, branch) ?: branch

    val timelines =
      try {
        PreviewHistory.read(repoDir, branch, layout.dir)
      } catch (e: Exception) {
        stderr(
          "compose-preview history-manifest: failed to read history from '$branch': ${e.message}"
        )
        exit(1)
      }

    // A resolvable ref with no render history means the read failed or matched nothing; refuse.
    if (timelines.isEmpty()) {
      val against =
        pathToPreviewId?.let { ", while baselines.json lists ${it.size} previews" }.orEmpty()
      stderr(
        "compose-preview history-manifest: '$branch' resolved but yielded no render history " +
          "under '${layout.dir}/'$against; refusing to write an empty manifest."
      )
      exit(1)
    }

    // On the image layout the join is derived from what git reported.
    val join = pathToPreviewId ?: PreviewHistoryManifest.imagePathsToPreviewIds(timelines.keys)
    if (join.isEmpty()) {
      stderr(
        "compose-preview history-manifest: none of the ${timelines.size} render paths under " +
          "'${layout.dir}/' on '$branch' could be keyed to a preview; refusing to write an " +
          "empty manifest."
      )
      exit(1)
    }
    val manifest = PreviewHistoryManifest.build(timelines, join, generatedFrom)

    output.absoluteFile.parentFile?.mkdirs()
    output.writeText(PreviewHistoryManifest.encode(manifest))

    if (!quiet) {
      val versions = manifest.previews.values.sumOf { it.versions.size }
      val unstable = manifest.previews.values.count { it.unstable }
      // Report drops explicitly: deleted or renamed previews are intentionally left out.
      val dropped = timelines.keys.count { it !in join }
      stdout(
        "compose-preview history-manifest: wrote ${output.path}: " +
          "${manifest.previews.size} previews, $versions versions, $unstable unstable" +
          if (dropped > 0) ", $dropped unmatched render paths dropped." else "."
      )
    }
  }

  private companion object {
    const val DEFAULT_BRANCH = "compose-preview/main"

    /** Keeps every pre-existing invocation on the baseline layout it was written for. */
    val DEFAULT_LAYOUT = PreviewHistoryManifest.Layout.RENDERS

    val USAGE =
      """
      Usage: compose-preview inspect history-manifest [options]

      Writes history.json for a baseline delivery branch: the per-preview render
      timeline a viewer reads instead of walking git. Not the same as
      `compose-preview history`, which inspects the daemon's reporting branch.

        --branch REF     Delivery-branch ref to read (default: $DEFAULT_BRANCH)
        --repo DIR       Repository to run git in (default: current directory)
        --output FILE    Where to write (default: ${PreviewHistoryManifest.FILE_NAME})
        --layout NAME    Branch layout: renders (default) or images. `renders` reads
                         renders/ and joins through baselines.json; `images` reads
                         images/ and derives ids from the paths, as the design
                         catalog branches (design-artifacts/<system>) are published.
        --baselines FILE Read baselines.json from here instead of from REF
                         (renders layout only)
        --quiet          Suppress the summary line
      """
        .trimIndent()

    fun List<String>.valueOf(flag: String): String? {
      val i = indexOf(flag)
      return if (i >= 0 && i + 1 < size) this[i + 1] else null
    }
  }
}

private fun gitShow(repoDir: File, ref: String, path: String): String? = runCatching {
  val p =
    ProcessBuilder("git", "show", "$ref:$path")
      .directory(repoDir)
      .redirectError(ProcessBuilder.Redirect.DISCARD)
      .start()
  val out = p.inputStream.bufferedReader().use { it.readText() }
  if (p.waitFor() == 0 && out.isNotBlank()) out else null
}
  .getOrNull()

/** Newest commit on [ref] that touched the renders tree, ignoring history-only commits. */
private fun renderTip(repoDir: File, ref: String, pathspec: String = "renders"): String? =
  runCatching {
    val p =
      ProcessBuilder("git", "rev-list", "-1", ref, "--", pathspec)
        .directory(repoDir)
        .redirectError(ProcessBuilder.Redirect.DISCARD)
        .start()
    val out = p.inputStream.bufferedReader().use { it.readText() }.trim()
    if (p.waitFor() == 0 && out.isNotEmpty()) out else null
  }
  .getOrNull()

private fun resolveSha(repoDir: File, ref: String): String? = runCatching {
  val p =
    ProcessBuilder("git", "rev-parse", ref)
      .directory(repoDir)
      .redirectError(ProcessBuilder.Redirect.DISCARD)
      .start()
  val out = p.inputStream.bufferedReader().use { it.readText() }.trim()
  if (p.waitFor() == 0 && out.isNotEmpty()) out else null
}
  .getOrNull()
