package ee.schimke.composeai.discovery

import kotlinx.serialization.Serializable

/**
 * A screen a builder composed out of components, in the shape a code generator can consume.
 *
 * This is deliberately **not** the UI builder's own document model. It is the narrow subset
 * [ScreenGenerator] needs — which component, what the user set, what went in each slot — so that
 * the generator can be tested and reasoned about without dragging an editor's undo stack, presence
 * state and collaboration protocol along with it. A builder projects its document onto this; the
 * projection is the builder's job and the interesting decisions are not in it.
 */
@Serializable
data class ScreenDocument(
  /** The generated composable's name. Must be a valid Kotlin identifier — the generator checks. */
  val name: String,
  val root: ScreenNode,
  /**
   * State the screen holds, declared before the tree that reads it.
   *
   * A list rather than a map because declaration order is emitted order, and a generated preamble
   * that reshuffles between runs is a diff nobody can review. Names must be unique and usable
   * Kotlin identifiers; the generator refuses otherwise.
   *
   * Empty for a static screen, which is every screen the generator could express before this.
   */
  val state: List<ScreenState> = emptyList(),
)

/**
 * One `mutableStateOf` the generated screen declares.
 *
 * @property name the Kotlin identifier the preamble binds and [ScreenValue.StateRead] names.
 * @property typeFqn what the state holds, checked against the parameter of every read. Declared
 *   rather than inferred from [initial]: a `String?` initialised to null is indistinguishable from
 *   any other nullable, and inferring `Boolean` from `false` would silently forbid a variable that
 *   is meant to widen later.
 * @property initial the starting value, generated by the same rules as any other argument — so a
 *   colour token or a construct works here exactly as it does on a parameter.
 */
@Serializable
data class ScreenState(val name: String, val typeFqn: String, val initial: ScreenValue)

/**
 * One placed component: which one, the arguments the user set, and what they dropped into its
 * slots.
 *
 * @property componentId a [ComponentRecord.canonicalId], or one of its
 *   [ComponentRecord.componentIds] catalog aliases. Both are accepted because the two sides name
 *   components differently and neither can be made to give: discovery's key is derived
 *   (`app/androidx.compose.material3.TextKt.Text`) precisely so an ordinary preview that carries no
 *   catalog identity still gets one, while a builder's document holds the authored id its palette
 *   was built from (`m3/text`). The record already carries that mapping, so resolving it here beats
 *   asking every builder to rebuild it. An alias claimed by two records is a refusal rather than a
 *   pick, and an id matching nothing is a refusal too — a builder pinned to a catalog it no longer
 *   has is exactly the case where inventing a call site produces confident nonsense.
 * @property arguments values the user set, by **source parameter name**. A name the component does
 *   not declare is a refusal: silently dropping it would generate a screen that compiles and is not
 *   the one that was designed.
 * @property slots children by slot name. A slot the component does not declare is likewise refused.
 */
@Serializable
data class ScreenNode(
  val componentId: String,
  val arguments: Map<String, ScreenValue> = emptyMap(),
  val slots: Map<String, List<ScreenNode>> = emptyMap(),
  /**
   * Handlers, by **source parameter name** — `onClick`, not a wire event name.
   *
   * Keyed the same way [arguments] is, and for the same reason: the generator writes a call site
   * against a recovered signature, so the only name it can bind is the one the function declares.
   * Mapping a catalog's event vocabulary onto parameter names is the projection's job, exactly as
   * it is for a property.
   *
   * A parameter that is not a zero-argument function type is refused rather than guessed at.
   */
  val handlers: Map<String, List<ScreenAction>> = emptyMap(),
)

/**
 * One statement a handler runs.
 *
 * Deliberately a closed set of assignments rather than an expression language: a generated lambda
 * that can compute is a generated lambda nobody can review, and the whole claim of this generator
 * is that its output is the screen somebody designed. Everything here writes one declared variable.
 */
@Serializable
sealed interface ScreenAction {
  /** The variable this action writes. It must be declared in [ScreenDocument.state]. */
  val variable: String

  /** `expanded.value = !expanded.value` — only valid on a `kotlin.Boolean`. */
  @Serializable data class Toggle(override val variable: String) : ScreenAction

  /**
   * `caption.value = "…"` — the value is generated by the same rules as any argument, and is
   * type-checked against the variable's declaration rather than trusted.
   */
  @Serializable data class Set(override val variable: String, val value: ScreenValue) : ScreenAction
}

/**
 * A value a builder can set on a parameter.
 *
 * ## Two halves, with different guarantees
 *
 * [Text], [Bool], [Whole] and [Fractional] are **self-evidently typed**: the generator knows what
 * `"hello"` and `false` are without being told, so it can reject `text = true` from the record
 * alone. That is the whole reason the first version of this interface held nothing else.
 *
 * It held nothing else for one release. A real builder document sets colours, dimensions, theme
 * tokens, enum entries, paddings and modifier chains, and measured against one — 19 `m3/text`
 * nodes, 18 colour tokens, 14 typography tokens, 11 paddings, 10 layout modifiers — the four
 * literal kinds covered under a third of the values placed. A generator that refuses two thirds of
 * a screen is not a generator anybody uses, so the vocabulary widened to the three shapes below:
 * [Reference] (`MaterialTheme.colorScheme.primary`), [Construct] (`PaddingValues(16.dp)`) and
 * [Chain] (`Modifier.fillMaxWidth()`).
 *
 * ## What the widening costs, stated plainly
 *
 * Those three carry a **claimed** [ScreenValue.typeFqn] rather than an evident one. The generator
 * still checks it against [TargetParameter.typeFqn] and still refuses a mismatch, so a colour
 * handed to a `String` parameter is caught exactly as `text = true` was — but it cannot check that
 * `MaterialTheme.colorScheme.primary` really *is* a `Color`. It takes the projection's word for
 * that one fact.
 *
 * That trade is deliberate and it is the smaller of two evils. The alternative was a table of
 * Material 3's token names inside a library that knows nothing about Material 3, maintained by
 * hand, wrong the first time a design system renamed a token. Instead the design system's own
 * knowledge stays with whoever has it, and what arrives here is a **restricted expression shape**:
 * a dotted path, a call, a chain of extension links. Not free text — every name is checked as
 * writable Kotlin and every reference is emitted fully qualified, so a projection cannot smuggle in
 * `run { System.exit(0) }` or shadow an import.
 *
 * A projection that gets a claimed type wrong produces source that does not compile. That failure
 * is loud, local and lands on the projection — which is the right place for it, and is why the
 * server-side compile check exists.
 */
@Serializable
sealed interface ScreenValue {

  /**
   * The fully-qualified classifier this value has, or null when the value is its own evidence.
   *
   * Null for the four literal kinds — nothing sensible could be claimed for `Whole(1)`, which fits
   * `Int` and `Long` alike and is checked against whichever the parameter declares.
   */
  val typeFqn: String?
    get() = null

  /**
   * `@RequiresOptIn` markers the expression needs, declared with `kotlin.RequiresOptIn`.
   *
   * The generator unions these into the wrapper's `@OptIn` exactly as it does for a component's
   * [ComponentCode.requiredOptIns]. It has to be declared rather than derived: a component's
   * markers come from the record, which discovery read off the class file, but a value names an
   * arbitrary allowed callable and nothing here has that callable's annotations. So a projection
   * reaching for an experimental accessor says so, and one that forgets gets a file the compiler
   * rejects — the same trade as [typeFqn], and the same reason it is written down here.
   */
  val requiredOptIns: List<String>
    get() = emptyList()

  /**
   * The subset of [requiredOptIns] declared with `androidx.annotation.RequiresOptIn`, which needs
   * `@androidx.annotation.OptIn(markerClass = […])` rather than `@kotlin.OptIn` — see
   * [ComponentCode.androidxOptIns] for why the two are not interchangeable.
   */
  val androidxOptIns: List<String>
    get() = emptyList()

  @Serializable data class Text(val value: String) : ScreenValue

  @Serializable data class Bool(val value: Boolean) : ScreenValue

  @Serializable data class Whole(val value: Long) : ScreenValue

  @Serializable data class Fractional(val value: Double) : ScreenValue

  /**
   * A `Float` literal — `1f`.
   *
   * Distinct from [Fractional] because the two differ only in a **spelling** the generator cannot
   * recover anywhere else. Against a declared parameter it does not need to: `Fractional` renders
   * as `1f` for a `kotlin.Float` and `1.0` for a `kotlin.Double`, because the parameter decides. In
   * a **nested** position — a constructor argument, a chain link's argument — there is no declared
   * type to render against, so the rule there is one fixed spelling per literal kind and a fraction
   * is always a `Double`.
   *
   * That rule left `Modifier.weight(…)` inexpressible. It takes a `Float`, it is an argument to a
   * chain link, and `weight(1.0)` does not compile — so a layout weight, which is one of the first
   * things anybody sets in a design tool, had no expression at all. This is the narrow addition
   * that gives it one, rather than making a nested `Fractional` guess at its own precision.
   */
  @Serializable data class Fractional32(val value: Float) : ScreenValue

  /**
   * A read through a fully-qualified path — `androidx.compose.material3.MaterialTheme.colorScheme
   * .primary`, `androidx.compose.ui.text.style.TextAlign.Center`.
   *
   * The [rootFqn] is **imported** and the path written from its simple name, so this reads
   * `Alignment.Start` and `MaterialTheme.colorScheme.primary` — what a person writes.
   *
   * It was emitted fully qualified for a while, and imported nowhere, on the reasoning that an
   * import can be shadowed by a same-named declaration in the package the caller chose for the
   * generated file while a qualified path cannot. The hazard is real and the trade was wrong: a
   * screen names `Modifier` and `MaterialTheme` on nearly every node, so the whole file paid for it
   * — `modifier = androidx.compose.ui.Modifier.size(24.dp)` is not a line anybody writes, and it is
   * half qualified anyway, since the `size` beside it is a [Chain] link and imports. What survives
   * of the reasoning is the conflict check, which refuses two roots claiming one simple name; the
   * caller's own package remains unknowable here, and a collision with it fails at the import line
   * rather than resolving to something else.
   *
   * Nothing about the type claim changes: there is no receiver to infer and no overload to resolve,
   * so the only thing the generator is trusting is still [typeFqn].
   *
   * @property rootFqn the qualified name the path starts from. A class (`…MaterialTheme`), an
   *   object, or a top-level property.
   * @property members further members read from it, in order. Empty for a bare object read.
   */
  @Serializable
  data class Reference(
    val rootFqn: String,
    val members: List<String> = emptyList(),
    override val typeFqn: String,
    override val requiredOptIns: List<String> = emptyList(),
    override val androidxOptIns: List<String> = emptyList(),
  ) : ScreenValue

  /**
   * A call to a fully-qualified callable — `androidx.compose.ui.graphics.Color(0xFF6750A4)`,
   * `androidx.compose.foundation.layout.PaddingValues(16.dp)`.
   *
   * Imported for the same reason [Reference] is, and by the same rule: a top-level declaration
   * imports itself and is written by simple name, while a member of an object imports the object,
   * so `CardDefaults.cardColors(…)` keeps the qualifier a person would write rather than collapsing
   * to a bare `cardColors(…)`. A constructor and a top-level factory function are the same shape
   * here on purpose: `Color(…)` is a function and `PaddingValues(…)` a constructor, the distinction
   * is invisible at the call site, and a record that made a projection declare which one would only
   * give it a second thing to get wrong.
   *
   * @property positional arguments in declaration order.
   * @property named arguments by parameter name, appended after [positional].
   */
  @Serializable
  data class Construct(
    val callableFqn: String,
    val positional: List<ScreenValue> = emptyList(),
    val named: Map<String, ScreenValue> = emptyMap(),
    override val typeFqn: String,
    override val requiredOptIns: List<String> = emptyList(),
    override val androidxOptIns: List<String> = emptyList(),
  ) : ScreenValue

  /**
   * A receiver followed by extension links — `Modifier.fillMaxWidth().padding(16.dp)`, `16.dp`.
   *
   * The one case that **must** import, and the reason it is a case of its own rather than a
   * [Reference] with a longer path: an extension is resolved from the importing file's scope, so
   * `Modifier.androidx.compose.foundation.layout.fillMaxWidth()` is not a spelling of anything.
   * Each link's callable is imported and called by its simple name, and two links claiming one
   * simple name from different packages are refused — Kotlin calls that a conflicting import, and
   * picking one would silently generate a chain nobody wrote.
   *
   * @property receiver what the links apply to. `Modifier` as a [Reference], or a literal for the
   *   `16` in `16.dp`.
   */
  /**
   * Reads a state variable the document declares.
   *
   * The variable must be declared in [ScreenDocument.state]; a read naming anything else is refused
   * rather than emitted, because the generated file would not compile and the failure would surface
   * as a Kotlin error about a name the designer never typed.
   *
   * Carries no opt-ins of its own: the declaration's [ScreenState.initial] carries them, and it is
   * the expression that actually names an API.
   */
  @Serializable
  data class StateRead(val variable: String, override val typeFqn: String) : ScreenValue

  @Serializable
  data class Chain(
    val receiver: ScreenValue,
    val links: List<ChainLink>,
    override val typeFqn: String,
    override val requiredOptIns: List<String> = emptyList(),
    override val androidxOptIns: List<String> = emptyList(),
  ) : ScreenValue
}

/**
 * One link in a [ScreenValue.Chain].
 *
 * @property callableFqn the extension's fully-qualified name. Imported, then called by simple name.
 * @property property a property read (`.dp`) rather than a call (`.padding(8.dp)`). A link that is
 *   both — a property with arguments — is a refusal, not a call.
 */
@Serializable
data class ChainLink(
  val callableFqn: String,
  val positional: List<ScreenValue> = emptyList(),
  val named: Map<String, ScreenValue> = emptyMap(),
  val property: Boolean = false,
  /**
   * The **implicit receiver** this link's extension is declared on, when it is a member extension
   * of a slot's scope rather than a top-level one — `androidx.compose.foundation.layout.RowScope`
   * for `Modifier.weight`, `androidx.compose.foundation.layout.BoxScope` for `matchParentSize`.
   *
   * Such a link is *not* imported. `RowScope.weight` is a member of `RowScope`, supplied by the
   * lambda's receiver, and neither `import …layout.RowScope.weight` nor a package-level
   * `…layout.weight` resolves — which is why a capitalised qualifier is otherwise refused outright.
   * What makes it legal instead is **where the node sits**: inside a slot whose
   * [TargetParameter.composableSlotReceiver] is this type, the receiver is in scope and the simple
   * name resolves.
   *
   * So this is a claim the generator **checks** rather than trusts, and it is the only thing that
   * makes a scoped modifier expressible without guessing. A node in a `Column` claiming `RowScope`
   * is refused by name, as is one claiming any scope at the root, where there is no receiver at
   * all. Null for an ordinary top-level extension, which imports as before.
   */
  val receiverScopeFqn: String? = null,
)
