package ee.schimke.composeai.plugin

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes `ee/schimke/composeai/renderer/robolectric.properties` into a
 * generated resources directory added to the `renderPreviews` test classpath.
 *
 * Robolectric reads package-level `robolectric.properties` from the classpath
 * and merges its fields into each test's `@Config`. `RobolectricRenderTestBase`
 * deliberately leaves `@Config.application` unset so this file can fill it in
 * without forcing every consumer onto the stub.
 *
 * Default ([useConsumerApplication] = false): the file pins
 * `application=android.app.Application`, so Robolectric creates a plain
 * Application and SKIPS the consumer's `onCreate()`. Consumer-side init that
 * depends on platform features Robolectric doesn't emulate (BridgingManager on
 * non-Wear sandboxes, Firebase, WorkManager, Play Services) no longer runs
 * during preview rendering.
 *
 * Opt-out ([useConsumerApplication] = true): the file is written without
 * `application=`, so Robolectric falls back to the manifest-declared
 * Application class. Intended for preview setups that genuinely require
 * their custom Application (e.g. Hilt's generated testing application).
 */
@CacheableTask
abstract class GenerateRobolectricPropertiesTask : DefaultTask() {
    @get:Input
    abstract val useConsumerApplication: Property<Boolean>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile.resolve("ee/schimke/composeai/renderer")
        dir.deleteRecursively()
        dir.mkdirs()
        val file = dir.resolve("robolectric.properties")
        val body = if (useConsumerApplication.get()) {
            """
            |# Generated by compose-ai-tools.
            |# useConsumerApplication=true — Robolectric falls back to the manifest-declared Application.
            |""".trimMargin()
        } else {
            """
            |# Generated by compose-ai-tools.
            |# Override the consumer's Application to a Robolectric-safe stub so
            |# preview rendering skips app-lifecycle side effects (DI, BridgingManager,
            |# Firebase, WorkManager, …). Set composePreview.useConsumerApplication = true
            |# to restore the manifest-declared Application.
            |application=android.app.Application
            |""".trimMargin()
        }
        file.writeText(body)
    }
}
