package ee.schimke.composeai.plugin

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes package-level `robolectric.properties` files into a generated resources directory on the
 * `composePreviewRender` test classpath: one for the composable lane (`…/renderer`), one for the
 * app-tour lane (`…/apptour`) and one for the daemon (`…/daemon`).
 *
 * `RobolectricRenderTestBase` carries no `@Config` / `@GraphicsMode`, so these files are the sole
 * source of `sdk=` ([resolveSdk]), `graphicsMode=NATIVE`, the global shadows, and `application=`.
 * Unless [useConsumerApplication] is set, the Application is pinned to a plain
 * `android.app.Application` so consumer `onCreate()` init (DI, Firebase, WorkManager, …) never runs
 * in the sandbox.
 */
@CacheableTask
abstract class GenerateRobolectricPropertiesTask : DefaultTask() {
  @get:Input abstract val useConsumerApplication: Property<Boolean>

  /**
   * [useConsumerApplication] for the app-tour lane (`kind=ACTIVITY` / `kind=APP_TOUR`). Defaults to
   * true on the extension: an Activity is the app, and a stub Application breaks Hilt / Koin
   * Activities.
   */
  @get:Input abstract val appTourUseConsumerApplication: Property<Boolean>

  /** Explicit `composePreview.sdkVersion`; out of range is a build failure. */
  @get:Input @get:Optional abstract val sdkOverride: Property<Int>

  /**
   * The consumer's `android.compileSdk`, captured in `finalizeDsl`. Values above the ceiling are
   * clamped with a warning rather than failing the build.
   */
  @get:Input @get:Optional abstract val consumerCompileSdk: Property<Int>

  /** Fallback when neither [sdkOverride] nor [consumerCompileSdk] is set (unit-test setups). */
  @get:Input abstract val defaultSdk: Property<Int>

  /**
   * Lifts [MAX_SUPPORTED_SDK] for the SDK matrix's snapshot probe cells, paired with a Robolectric
   * snapshot that ships the higher API (`composeai.matrix.maxSupportedSdk`). Deliberately not on
   * the public extension.
   */
  @get:Input @get:Optional abstract val maxSupportedSdkOverride: Property<Int>

  /**
   * Major version of the JVM the render test forks into; defaults to the running JVM. Below
   * [MIN_JAVA_FOR_SDK_36] the ceiling drops to [MAX_SUPPORTED_SDK_BELOW_JAVA_21], since Robolectric
   * otherwise fails every render with an opaque `UnsupportedOperationException`. The daemon pins
   * the same level (`RobolectricHost.ANDROID_SDK`).
   */
  @get:Input @get:Optional abstract val buildJavaMajor: Property<Int>

  @get:OutputDirectory abstract val outputDir: DirectoryProperty

  @TaskAction
  fun generate() {
    val sdkLevel = resolveSdk()
    val dir = outputDir.get().asFile.resolve("ee/schimke/composeai/renderer")
    dir.deleteRecursively()
    dir.mkdirs()
    val file = dir.resolve("robolectric.properties")
    // Global shadows, each inert when the consumer lacks the library:
    // - `ShadowFontsContractCompat`: GoogleFont renders without a per-test `@Config`.
    // - `ShadowAsyncImagePainter`: coil 2 loads images instead of a preview placeholder (#2952).
    // - `ShadowWearTimeSource`: Wear `TimeText` shows a fixed 10:10 (#3239).
    // - `ShadowPausedClockHardwareRenderer`: keeps hwui frame timestamps on the paused clock, so
    //   render-thread animations are reproducible (#4578); the daemon registers the same shadow.
    // - `ShadowSdkGestureInputManager`: Wear M3 one-handed gestures work off-watch.
    // `ShadowContextWrapperPermissionTracker` is deliberately daemon-only (#3698);
    // `GenerateRobolectricPropertiesTaskTest` pins its absence.
    val shadowsLine =
      "shadows=ee.schimke.composeai.renderer.ShadowFontsContractCompat," +
        "ee.schimke.composeai.renderer.ShadowAsyncImagePainter," +
        "ee.schimke.composeai.renderer.ShadowWearTimeSource," +
        "ee.schimke.composeai.renderer.ShadowPausedClockHardwareRenderer," +
        "ee.schimke.composeai.daemon.ShadowSdkGestureInputManager"
    // Robolectric can only shadow classes it instruments. Entries are class-name prefixes, so
    // naming `ResourcesKt` instruments just the class `ShadowWearTimeSource` targets.
    val instrumentedPackagesLine =
      "instrumentedPackages=coil.compose,androidx.wear.compose.materialcore.ResourcesKt," +
        "androidx.wear.compose.material3.onehandedgesture.SdkGestureInputManagerImpl"
    // Not on `@Config`: JUnit resolving `@Config.application()`'s default during discovery can
    // throw
    // `ClassNotFoundException: android.app.Application` (#142).
    val sdkLine = "sdk=$sdkLevel"
    val graphicsLine = "graphicsMode=NATIVE"
    val body =
      if (useConsumerApplication.get()) {
        """
            |# Generated by compose-ai-tools.
            |# useConsumerApplication=true — Robolectric falls back to the manifest-declared Application.
            |$sdkLine
            |$graphicsLine
            |$shadowsLine
            |$instrumentedPackagesLine
            |"""
          .trimMargin()
      } else {
        """
            |# Generated by compose-ai-tools.
            |# Override the consumer's Application to a Robolectric-safe stub so
            |# preview rendering skips app-lifecycle side effects (DI, BridgingManager,
            |# Firebase, WorkManager, …). Set composePreview.useConsumerApplication = true
            |# to restore the manifest-declared Application.
            |application=android.app.Application
            |$sdkLine
            |$graphicsLine
            |$shadowsLine
            |$instrumentedPackagesLine
            |"""
          .trimMargin()
      }
    file.writeText(body)

    // The app-tour lane ([ee.schimke.composeai.apptour.AppTourRobolectricRenderTest]) has its own
    // class because Robolectric resolves the Application per test class. Its package is a sibling,
    // not nested under `…renderer`, so it doesn't inherit the stub `application=` line. The other
    // fields are copied so activities and composables render identically.
    val appTourDir = outputDir.get().asFile.resolve("ee/schimke/composeai/apptour")
    appTourDir.deleteRecursively()
    appTourDir.mkdirs()
    val appTourApplicationLine =
      if (useConsumerApplication.get() || appTourUseConsumerApplication.get()) {
        "# Application omitted — Robolectric falls back to the manifest-declared Application, " +
          "which is what an Activity needs."
      } else {
        "application=android.app.Application"
      }
    appTourDir
      .resolve("robolectric.properties")
      .writeText(
        """
            |# Generated by compose-ai-tools — the kind=ACTIVITY / kind=APP_TOUR render lane.
            |# Set composePreview.appTourUseConsumerApplication = false to render activities against
            |# a stub Application instead (they then skip the app's own onCreate, and any that need
            |# app-level DI will fail).
            |$appTourApplicationLine
            |$sdkLine
            |$graphicsLine
            |$shadowsLine
            |$instrumentedPackagesLine
            |"""
          .trimMargin()
      )

    // The daemon's [ee.schimke.composeai.daemon.RobolectricHost.SandboxRunner] only reads its own
    // package's file, and Robolectric 4.16 no longer merges the deprecated `buildGlobalConfig`
    // Application override, so without this the consumer's `onCreate()` crashes every sandbox.
    // `sdk` / `graphicsMode` come from `@Config` on `SandboxRunner`.
    val daemonDir = outputDir.get().asFile.resolve("ee/schimke/composeai/daemon")
    daemonDir.deleteRecursively()
    daemonDir.mkdirs()
    val daemonFile = daemonDir.resolve("robolectric.properties")
    val daemonBody =
      if (useConsumerApplication.get()) {
        """
        |# Generated by compose-ai-tools.
        |# useConsumerApplication=true — the daemon's Robolectric falls back to the
        |# manifest-declared Application.
        |"""
          .trimMargin()
      } else {
        """
        |# Generated by compose-ai-tools.
        |# Override the consumer's Application to a Robolectric-safe stub for daemon-driven preview
        |# rendering, so app-lifecycle init (DI, Firebase, WorkManager, …) never runs and crashes
        |# the render sandbox. sdk/graphicsMode are supplied by @Config/@GraphicsMode on the
        |# daemon's SandboxRunner; only the Application override needs this file because Robolectric
        |# 4.16 no longer merges the deprecated buildGlobalConfig override over the manifest.
        |application=android.app.Application
        |"""
          .trimMargin()
      }
    daemonFile.writeText(daemonBody)
  }

  /**
   * Priority chain: [sdkOverride] (strict) → [consumerCompileSdk] (clamp to range with warning) →
   * [defaultSdk]. Internal so the test can drive it directly.
   */
  internal fun resolveSdk(): Int {
    val javaMajor = buildJavaMajor.orNull ?: Runtime.version().feature()
    // The jar ceiling, lowered when the test JVM is too old for the top level.
    val jarCeiling = maxSupportedSdkOverride.orNull ?: MAX_SUPPORTED_SDK
    val ceiling =
      if (javaMajor < MIN_JAVA_FOR_SDK_36) minOf(jarCeiling, MAX_SUPPORTED_SDK_BELOW_JAVA_21)
      else jarCeiling
    if (sdkOverride.isPresent) {
      val v = sdkOverride.get()
      if (v !in MIN_SUPPORTED_SDK..ceiling) {
        throw GradleException(
          "compose-preview: composePreview.sdkVersion = $v is outside the supported range " +
            "($MIN_SUPPORTED_SDK..$ceiling for this Robolectric build${jdkCeilingSuffix(javaMajor, ceiling, jarCeiling)}). " +
            "Pick a value inside that range or remove the override to let the plugin auto-detect " +
            "from android.compileSdk."
        )
      }
      return v
    }
    if (consumerCompileSdk.isPresent) {
      val raw = consumerCompileSdk.get()
      if (raw < MIN_SUPPORTED_SDK) {
        throw GradleException(
          "compose-preview: consumer compileSdk = $raw is below Robolectric's floor " +
            "($MIN_SUPPORTED_SDK). Raise android.compileSdk or set composePreview.sdkVersion = N " +
            "to pin a supported level explicitly."
        )
      }
      if (raw > ceiling) {
        val jdkClamped = ceiling < jarCeiling && raw <= jarCeiling
        logger.warn(
          if (jdkClamped) {
            "compose-preview: consumer compileSdk = $raw needs JDK $MIN_JAVA_FOR_SDK_36+ to render " +
              "(Robolectric refuses an SDK > $MAX_SUPPORTED_SDK_BELOW_JAVA_21 sandbox on JDK " +
              "$javaMajor); clamping the Robolectric sandbox to $ceiling. Run the render on JDK " +
              "$MIN_JAVA_FOR_SDK_36+ to render at $raw, or set composePreview.sdkVersion = N to " +
              "silence this warning."
          } else {
            "compose-preview: consumer compileSdk = $raw exceeds Robolectric's max supported SDK " +
              "($ceiling for this Robolectric build); clamping the Robolectric sandbox " +
              "to $ceiling. Rendering may still fail if your APK's <uses-sdk> requires a " +
              "newer framework. Set composePreview.sdkVersion = N to silence this warning."
          }
        )
        return ceiling
      }
      return raw
    }
    return defaultSdk.get()
  }

  /** Names the JDK gate in the override error when it lowered the ceiling. */
  private fun jdkCeilingSuffix(javaMajor: Int, ceiling: Int, jarCeiling: Int): String =
    if (ceiling < jarCeiling)
      "; SDK > $ceiling needs JDK $MIN_JAVA_FOR_SDK_36+, this build is on JDK $javaMajor"
    else ""

  companion object {
    /** Lowest API with an `android-all-instrumented` jar. */
    internal const val MIN_SUPPORTED_SDK: Int = 21

    /**
     * Highest API the bundled Robolectric ships a jar for; bump with `libs.robolectric`. The
     * effective ceiling can be lower on old JDKs; see [buildJavaMajor].
     */
    internal const val MAX_SUPPORTED_SDK: Int = 36

    /** First API Robolectric refuses to bootstrap below JDK [MIN_JAVA_FOR_SDK_36]. */
    internal const val SDK_REQUIRING_JAVA_21: Int = 36

    internal const val MIN_JAVA_FOR_SDK_36: Int = 21

    /** Ceiling below JDK [MIN_JAVA_FOR_SDK_36]; mirrors `RobolectricHost.ANDROID_SDK`. */
    internal const val MAX_SUPPORTED_SDK_BELOW_JAVA_21: Int = 35

    /** SDK when nothing else sets one; AGP requires `compileSdk`, so only unit tests reach it. */
    internal const val DEFAULT_SDK: Int = 35
  }
}
