package ee.schimke.composeai.themepin.compiler

import java.io.File
import org.jetbrains.kotlin.cli.common.ExitCode
import org.jetbrains.kotlin.cli.jvm.K2JVMCompiler
import org.jetbrains.org.objectweb.asm.ClassReader
import org.jetbrains.org.objectweb.asm.ClassVisitor
import org.jetbrains.org.objectweb.asm.MethodVisitor
import org.jetbrains.org.objectweb.asm.Opcodes
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

/**
 * Compiles a fixture with the real Kotlin and Compose compilers, with and without this plugin, and
 * reads the `MaterialTheme` call out of the generated bytecode.
 */
class ThemePinCompilerPluginTest {

  @get:Rule val tempFolder: TemporaryFolder = TemporaryFolder()

  private val fixture =
    """
    package fixture

    import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
    import androidx.compose.material3.MaterialTheme
    import androidx.compose.material3.MotionScheme
    import androidx.compose.material3.darkColorScheme
    import androidx.compose.runtime.Composable

    @Composable
    fun AppTheme(content: @Composable () -> Unit) {
      MaterialTheme(colorScheme = darkColorScheme(), content = content)
    }

    @OptIn(ExperimentalMaterial3ExpressiveApi::class)
    @Composable
    fun ExpressiveAppTheme(content: @Composable () -> Unit) {
      MaterialTheme(colorScheme = darkColorScheme(), motionScheme = MotionScheme.expressive(), content = content)
    }

    @Composable
    fun ReadsTheTheme(): Any = MaterialTheme.colorScheme
    """
      .trimIndent()

  @Test
  fun bothMaterialThemeOverloadsAreRedirected() {
    val calls = compile(withPlugin = true)
    assertEquals(
      listOf(
        "AppTheme" to ThemePinClassGeneratorExtension.PREVIEW_THEME_OWNER,
        "ExpressiveAppTheme" to ThemePinClassGeneratorExtension.PREVIEW_THEME_OWNER,
      ),
      calls.map { it.caller to it.owner },
    )
    assertTrue(
      "the redirect must keep the descriptor Material 3 was called with",
      calls.all { it.descriptor in ThemePinClassGeneratorExtension.REDIRECTS },
    )
  }

  @Test
  fun withoutThePluginMaterial3IsCalled() {
    val calls = compile(withPlugin = false)
    assertEquals(
      listOf(ThemePinClassGeneratorExtension.MATERIAL_THEME_OWNER).repeat(2),
      calls.map { it.owner },
    )
    assertTrue(
      "every descriptor Material 3 is called with must have a twin in the runtime",
      calls.all { it.descriptor in ThemePinClassGeneratorExtension.REDIRECTS },
    )
  }

  @Test
  fun theRuntimeDeclaresATwinForEveryRedirect() {
    val runtime =
      Class.forName(ThemePinClassGeneratorExtension.PREVIEW_THEME_OWNER.replace('/', '.'))
        .declaredMethods
        .filter { it.name == ThemePinClassGeneratorExtension.PREVIEW_THEME_NAME }
        .map { org.jetbrains.org.objectweb.asm.Type.getMethodDescriptor(it) }
        .toSet()
    assertEquals(ThemePinClassGeneratorExtension.REDIRECTS, runtime)
  }

  private data class ThemeCall(val caller: String, val owner: String, val descriptor: String)

  private fun compile(withPlugin: Boolean): List<ThemeCall> {
    val src = tempFolder.newFolder().resolve("Fixture.kt").apply { writeText(fixture) }
    val out = tempFolder.newFolder()
    val plugins = buildList {
      add(System.getProperty("themePin.composePluginJar"))
      if (withPlugin) add(System.getProperty("themePin.pluginJar"))
    }
    val args = buildList {
      add(src.absolutePath)
      add("-d")
      add(out.absolutePath)
      add("-classpath")
      add(System.getProperty("java.class.path"))
      add("-no-stdlib")
      add("-no-reflect")
      add("-jvm-target")
      add("17")
      plugins.forEach { add("-Xplugin=$it") }
    }
    val exit = K2JVMCompiler().exec(System.err, *args.toTypedArray())
    assertEquals("fixture failed to compile", ExitCode.OK, exit)
    return themeCalls(out.resolve("fixture/FixtureKt.class"))
  }

  private fun themeCalls(classFile: File): List<ThemeCall> {
    val calls = mutableListOf<ThemeCall>()
    ClassReader(classFile.readBytes())
      .accept(
        object : ClassVisitor(Opcodes.API_VERSION) {
          override fun visitMethod(
            access: Int,
            name: String,
            descriptor: String,
            signature: String?,
            exceptions: Array<out String>?,
          ): MethodVisitor =
            object : MethodVisitor(Opcodes.API_VERSION) {
              override fun visitMethodInsn(
                opcode: Int,
                owner: String,
                calleeName: String,
                calleeDescriptor: String,
                isInterface: Boolean,
              ) {
                if (
                  opcode == Opcodes.INVOKESTATIC &&
                    (calleeName == ThemePinClassGeneratorExtension.MATERIAL_THEME_NAME ||
                      calleeName == ThemePinClassGeneratorExtension.PREVIEW_THEME_NAME)
                ) {
                  calls += ThemeCall(name, owner, calleeDescriptor)
                }
              }
            }
        },
        0,
      )
    return calls
  }

  private fun <T> List<T>.repeat(times: Int): List<T> = (1..times).flatMap { this }
}
