package ee.schimke.composeai.plugin

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import java.net.URLClassLoader
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class GeneratePoolingContainerRTaskTest {

  @get:Rule val tempDir = TemporaryFolder()

  private fun loadShim(ids: Map<String, Int> = GeneratePoolingContainerRTask.TAG_IDS): Class<*> {
    val root = tempDir.newFolder()
    val packageDir = root.resolve(GeneratePoolingContainerRTask.PACKAGE_PATH).apply { mkdirs() }
    packageDir.resolve("R\$id.class").writeBytes(GeneratePoolingContainerRTask.classBytes(ids))
    val loader = URLClassLoader(arrayOf(root.toURI().toURL()), null)
    return loader.loadClass(GeneratePoolingContainerRTask.CLASS_NAME)
  }

  @Test
  fun `the generated class carries exactly the two ids PoolingContainer reads`() {
    // The AAR's own R.txt declares these two and nothing else:
    //   int id is_pooling_container_tag 0x0
    //   int id pooling_container_listener_holder_tag 0x0
    val fields = loadShim().declaredFields.associate { it.name to it.getInt(null) }

    assertThat(fields.keys)
      .containsExactly("is_pooling_container_tag", "pooling_container_listener_holder_tag")
  }

  @Test
  fun `every id is a legal View tag key`() {
    // `View.setTag(int, Object)` throws IllegalArgumentException("The key must be an
    // application-specific resource id") when `key ushr 24` is below 2. That is exactly why the
    // AAR's compile-time R — where both ids are the 0x0 placeholder — cannot be used at runtime,
    // and it is the one property of these values that is not arbitrary.
    for ((name, value) in GeneratePoolingContainerRTask.TAG_IDS) {
      assertWithMessage(name).that(value ushr 24).isAtLeast(2)
    }
  }

  @Test
  fun `the ids cannot collide with a resource id AGP generates`() {
    // App and library resources land in the 0x7f package. Staying in 0x7e is what makes a
    // collision with a real tag key on the same view — androidx.compose.ui.R.id.* among them —
    // impossible rather than merely unlikely.
    for (value in GeneratePoolingContainerRTask.TAG_IDS.values) {
      assertThat(value ushr 24).isEqualTo(0x7e)
    }
  }

  @Test
  fun `the two ids are distinct`() {
    // They key different tags on the same view; equal values would make one clobber the other.
    assertThat(GeneratePoolingContainerRTask.TAG_IDS.values.toSet())
      .hasSize(GeneratePoolingContainerRTask.TAG_IDS.size)
  }

  @Test
  fun `the fields are readable exactly as a getstatic resolves them`() {
    // What PoolingContainer.<clinit> actually does is
    // `getstatic androidx/customview/poolingcontainer/R$id.pooling_container_listener_holder_tag :
    // I`,
    // so the test loads the generated bytes in a bare classloader and reads the fields back.
    val loaded = loadShim(mapOf("is_pooling_container_tag" to 0x7e0f0009))

    val field = loaded.getField("is_pooling_container_tag")
    assertThat(field.type).isEqualTo(Int::class.javaPrimitiveType)
    assertThat(field.getInt(null)).isEqualTo(0x7e0f0009)
  }
}
